### ISSUE TITLE
Couldn't send "m" key 

### ISSUE THREAD

**Issue by peoplewhite** [jamessa/Pragmatic#3]
Couldn't send "m" key signal when keyboard was initialized. It will be enabled after pressing it repeatedly. Weird.

This config will be OK.
![photo_2022-05-05 21 56 52](https://user-images.githubusercontent.com/5237076/166939169-e7fd0769-c5a8-4ee8-b98e-71554ddf17e0.jpeg)

This config will cause this issue I mentioned as title.
![photo_2022-05-05 21 56 48](https://user-images.githubusercontent.com/5237076/166939182-1c0b3974-0b74-41ff-82a1-d074546cccf5.jpeg)

**Comment by jamessa** [comment]
try with original qmk code base.
try disable Nkro.
try different USB cable
try different key switch

**Comment by jamessa** [comment]
It turns out to be a misconfiguration. In Combos tab,  `M` was accidentally set as first key of a combo. By clearing the combos, everything back to normal.

![photo_2022-05-09 15 33 39](https://user-images.githubusercontent.com/188772/167747430-9e35ccf8-51c8-4c7f-aea9-b0785331582b.jpeg)

@peoplewhite please verify.

**Comment by peoplewhite** [comment]
totally fixed. appreciate it. ❤️
